version: '3.1'
services:
  schedule_bot_app:
    build: ../
    image: schedule_bot_app
    container_name: schedule_bot_app
    restart: always
    env_file:
      - .env

  mongo:
    image: mongo:5.0.14
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TASK_HANDLER: ${TASK_HANDLER}
      TASK_HANDLER_PASSWORD: ${TASK_HANDLER_PASSWORD}
    volumes:
      - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
      - ../mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_HOST_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
